apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hello-app-docker
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'hello-app-docker:latest'
  runPolicy: Serial
  source:
    git:
      ref: main
      uri: 'https://github.com/s19004162/hello-app.git'
    sourceSecret:
      name: s19004162
    type: Git
  strategy:
    dockerStrategy:
    type: Docker
  triggers:
    - imageChange:
        lastTriggeredImageID: >-
          172.30.1.1:5000/openshift/python@sha256:ac50754646f0d37616515fb30467d8743fb12954260ec36c9ecb5a94499447e0
      type: ImageChange
    - type: ConfigChange
    - generic:
        secret: 233967fca60cd96c
      type: Generic
    - github:
        secret: d90fa5d4c850f208
      type: GitHub
status:
  lastVersion: 4
